import uuid
import json
from fastapi import APIRouter, Depends, HTTPException, status
from sqlmodel import Session
from app.models.spec import GenerationRequest, FiboSpec
from app.models.history import GenerationHistory
from app.core.database import get_session
from app.core.fibo_service import fibo_service
from typing import Dict, Any

router = APIRouter()

# Define the response model for clarity
class GenerationResponse(GenerationHistory):
    """
    Inherits from the history model but is used as the response body.
    We exclude the 'id' field as it's generated by the DB.
    """
    class Config:
        json_schema_extra = {
            "example": {
                "uuid": "gen-a3b4c5d6",
                "generated_image_url": "https://storage.com/images/gen-a3b4c5d6.jpg",
                "status": "success",
                "spec": {
                    "product_name": "Leather Sneaker",
                    "scene_description": "on a clean white studio table",
                    "camera": {"angle": "eye-level", "fov": "normal", "aspect_ratio": "1:1"},
                    "lighting": {"style": "studio soft light", "color_temperature": "neutral"}
                },
                "created_at": "2025-12-12T12:00:00.000Z"
            }
        }

@router.post(
    "/generate", 
    response_model=GenerationResponse, 
    status_code=status.HTTP_201_CREATED,
    summary="Generate a reproducible image set from a structured Visual Spec"
)
def generate_image(
    request: GenerationRequest, # FastAPI automatically validates this using Pydantic!
    session: Session = Depends(get_session)
) -> Any:
    """
    Receives a FiboSpec, calls the FIBO API, and records the exact input spec 
    and the output URL to the database for versioning and reproducibility.
    """
    
    # 1. Validation (Handled by FastAPI/Pydantic automatically before this function runs)
    fibo_spec: FiboSpec = request.spec
    
    try:
        # 2. Call the FIBO Service
        # The service handles transforming the FiboSpec into the Bria/FIBO JSON payload
        fibo_result = fibo_service.generate_image(fibo_spec)

        if not fibo_result.get("success"):
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"FIBO API generation failed: {fibo_result.get('error', 'Unknown error')}"
            )
            
        # 3. Prepare data for Persistence
        generation_uuid = f"gen-{uuid.uuid4().hex[:8]}"
        
        # We store the spec as a JSON dictionary (dict) derived from the Pydantic model
        # The dict() method converts the Pydantic model back into a standard Python dict
        spec_dict = fibo_spec.model_dump()
        
        history_entry = GenerationHistory(
            uuid=generation_uuid,
            spec=spec_dict,
            generated_image_url=fibo_result["image_data_url"],
            status="success"
        )
        
        # 4. Persistence (Save to Database)
        session.add(history_entry)
        session.commit()
        session.refresh(history_entry)
        
        # 5. Return the full history entry as the response
        return history_entry
        
    except Exception as e:
        print(f"Generation Error: {e}")
        # Re-raise as HTTP 500 if it's an unexpected error (like DB or internal service failure)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An internal error occurred during generation: {e}"
        )